### ISSUE TITLE
Sad Meme ☹️

### ISSUE THREAD

**Issue by aleff-github** [dayt0n/USB-TCP#1]
When you find that it doesn't really do a search and it doesn't really find a device:

![image](https://github.com/dayt0n/USB-TCP/assets/58374531/c4ba50d8-a21c-4124-9af3-5ebcf151ef93)
```
clear
echo "Searching for Device..."
sleep 1
echo "Device Found!"
sleep 0.5
```

**Comment by dayt0n** [comment]
lol, I think I had just discovered the `sleep` command at the time
